version: "3.8"
networks:
  employee-network:
services:
  db:
    image: postgres
    restart: always
    volumes:
      - db-vol:/var/lib/postgresql/data
    ports:
      - "5400:5432"
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER: juba
      POSTGRES_DB: hibernate
    secrets:
      - db_password
    networks:
      - employee-network
  employee-management:
    image: bellsoft/liberica-openjdk-alpine:latest
    working_dir: /
    volumes:
      - ./target/employee-management-3.1.3.jar:/employee-management-3.1.3.jar
    ports:
      - "3000:3000"
    mem_swappiness: 300
    depends_on:
      db:
        condition: service_started
    cpus: 1.5
    mem_limit: 2048m
    networks:
      - employee-network
    command: java -Xms512m -Xmx1024m -Dspring.profiles.active=docker -jar ./employee-management-3.1.3.jar # You should create your own docker config property
secrets:
  db_password:
    file: secrets/db/password.txt
volumes:
  db-vol: